name: Validate Shell Scripts

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    name: Validate shell scripts
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: '.'
        format: gcc
        severity: warning
        
    - name: Test script syntax
      run: |
        bash -n canvas-assign-creator.sh
        bash -n canvas-assign-simple.sh
        
    - name: Check dependencies documentation
      run: |
        echo "Checking if required dependencies are documented..."
        grep -q "curl" README.md && echo "✓ curl documented"
        grep -q "jq" README.md && echo "✓ jq documented"